### ISSUE TITLE
Bug in MaveDB API urls

### ISSUE THREAD

**Issue by daniaki** [VariantEffect/rapimave#2]
The upcoming version of MaveDB fixes a bug allowing API calls to omit the model type directory. Currently `/api/<urn>/` works but in the next update this will return a 404. The intended urls are:

- `/api/scoresets/<urn>/<file>/`
- `/api/experimentsets/<urn>/`
- `/api/experiments/<urn>/`

I can fork this package and submit a PR if you would like?

**Comment by jweile** [comment]
Thanks! It sounds like a relative straight-forward change. I'll see that I get it implemented by Monday. You can submit a pull request if you like, but I don't think it's necessary. 

Thanks again!

**Comment by jweile** [comment]
Fix is now committed, however not yet deployed to the latest version of mavevis.

**Comment by jweile** [comment]
Now deployed to production.
